### ISSUE TITLE
Go: How to iterate through contained resource

### ISSUE THREAD

**Issue by citizenrich** [google/fhir-examples#11]
Thanks for the great examples. With the Go parse patients example, can you give a hint on how to iterate through all patients that have been unmarshalled? I only see one, and the usual output of Patient.ndjson from Synthea is multiple. I only see the first one and I don't see a function to choose an index/slice.

https://github.com/google/fhir-examples/blob/aba538600be191e56e37e394fa9ec18f753e712b/go/google/fhir_examples/parse/parse_patients.go#L68

**Comment by hawyar** [comment]
```go
scanner := bufio.NewScanner(bytes.NewReader(file))

for scanner.Scan() {
	line := scanner.Bytes()
	
	if err != nil {
		log.Fatal(err)
	}

	um, err := jsonformat.NewUnmarshaller("UTC",fhirversion.R4)

	if err != nil {
		log.Fatal(err)
	}

	unmarshalled, err := um.Unmarshal(line)

	if err != nil {
		log.Fatal(err)
	}

	contained := unmarshalled.(*r4pb.ContainedResource)
	patient := contained.GetPatient()
	
	fmt.Println("patient: ", patient.GetName()[0].GetGiven()[0].GetValue())
}

if err := scanner.Err(); err != nil {
	log.Fatal(err)
}
```

**Comment by citizenrich** [comment]
Thanks much.
