### ISSUE TITLE
Following the guide gives errors when running ./generate_synthea.sh

### ISSUE THREAD

**Issue by zhihao0040** [google/fhir-examples#3]
I tried following the guide available on this repo's README.
I am using a ubuntu virtual machine on virtualbox.

Encountering errors such as:
'''
INFO: Call stack for the definition of repository 'fhir_bazel_pip_dependencies' which is a pip_import (rule definition at /home/zhihaotan/.cache/bazel/_bazel_zhihaotan/9b5b980c5e264403b4ce49ee1b642806/external/rules_python/python/pip.bzl:42:14):
 - /home/zhihaotan/.cache/bazel/_bazel_zhihaotan/9b5b980c5e264403b4ce49ee1b642806/external/com_google_fhir/bazel/workspace.bzl:10:5
 - /home/zhihaotan/git/fhir-examples/WORKSPACE:18:1

ERROR: An error occurred during the fetch of repository 'fhir_bazel_pip_dependencies':
   pip_import failed:  ()
ERROR: no such package '@fhir_bazel_pip_dependencies//': pip_import failed:  ()
ERROR: no such package '@fhir_bazel_pip_dependencies//': pip_import failed:  ()
INFO: Elapsed time: 18.796s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
./generate-synthea.sh: line 38: bazel-bin/external/com_google_fhir/java/SplitBundleMain: No such file or directory
mkdir: cannot create directory ‘/home/zhihaotan/fhirdata/analytic/’: File exists
mv: cannot stat '/home/zhihaotan/fhirdata/ndjson/*.schema.json': No such file or directory
mv: cannot stat '/home/zhihaotan/fhirdata/ndjson/*.analytic.ndjson': No such file or directory
Done
'''

Could I please get some help on this as well as on the tensorflow's guide?

**Comment by jamesthompson** [comment]
@zhihao0040 I think the problem could be indicated by this line: 
`mkdir: cannot create directory ‘/home/zhihaotan/fhirdata/analytic/’: File exists`

It looks like where you're running from the directory already exists and the generate-synthea.sh script is trying to remake it.

**Comment by nickgeorge** [comment]
Gonna close this for now, feel free to reopen if you're still having problems.  Sorry, I'm working on getting better at responding
